"""@generated by npm_translate_lock(name = "npm", pnpm_lock = "//:pnpm-lock.yaml")"""

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//js:defs.bzl", _js_library = "js_library")
load("@@npm__at_aspect-test_a__5.0.2__links//:defs.bzl", store_0 = "npm_imported_package_store")
load("@@npm__at_aspect-test_b__5.0.2__links//:defs.bzl", link_1 = "npm_link_imported_package_store", store_1 = "npm_imported_package_store")
load("@@npm__at_aspect-test_c__2.0.2__links//:defs.bzl", store_2 = "npm_imported_package_store")
load("@@npm__at_aspect-test_d__2.0.0__at_aspect-test_c_2.0.2__links//:defs.bzl", store_3 = "npm_imported_package_store")
load("@@npm__is-number__6.0.0__links//:defs.bzl", store_4 = "npm_imported_package_store")
load("@@npm__is-odd__3.0.1__links//:defs.bzl", link_5 = "npm_link_imported_package_store", store_5 = "npm_imported_package_store")

# buildifier: disable=function-docstring
def npm_link_all_packages(name = "node_modules", imported_links = []):
    root_package = ""
    link_packages = [""]
    bazel_package = native.package_name()
    is_root = bazel_package == root_package
    link = bazel_package in link_packages
    if not is_root and not link:
        msg = "The npm_link_all_packages() macro loaded from @npm//:defs.bzl and called in bazel package '%s' may only be called in bazel packages that correspond to the pnpm root package or pnpm workspace projects. Projects are discovered from the pnpm-lock.yaml and may be missing if the lockfile is out of date. Root package: '', pnpm workspace projects: ''" % native.package_name()
        fail(msg)
    link_targets = []
    scope_targets = {}

    for link_fn in imported_links:
        new_link_targets, new_scope_targets = link_fn(name)
        link_targets.extend(new_link_targets)
        for _scope, _targets in new_scope_targets.items():
            scope_targets[_scope] = scope_targets[_scope] + _targets if _scope in scope_targets else _targets

    if is_root:
        store_0(name = "{}/@aspect-test/a".format(name))
        store_1(name = "{}/@aspect-test/b".format(name))
        store_2(name = "{}/@aspect-test/c".format(name))
        store_3(name = "{}/@aspect-test/d".format(name))
        store_4(name = "{}/is-number".format(name))
        store_5(name = "{}/is-odd".format(name))
    if link:
        if native.package_name() == "":
            link_1(name = "{}/@aspect-test/b".format(name))
            link_targets.append("//{}:{}/@aspect-test/b".format(bazel_package, name))
            scope_targets["@aspect-test"] = scope_targets["@aspect-test"] + [link_targets[-1]] if "@aspect-test" in scope_targets else [link_targets[-1]]
            link_5(name = "{}/is-odd".format(name))
            link_targets.append("//{}:{}/is-odd".format(bazel_package, name))

    for scope, scoped_targets in scope_targets.items():
        _js_library(
            name = "{}/{}".format(name, scope),
            srcs = scoped_targets,
            tags = ["manual"],
            visibility = ["//visibility:public"],
        )

    _js_library(
        name = name,
        srcs = link_targets,
        tags = ["manual"],
        visibility = ["//visibility:public"],
    )

# buildifier: disable=function-docstring
def npm_link_targets(name = "node_modules", package = None):
    link_packages = [""]
    bazel_package = package if package != None else native.package_name()
    link = bazel_package in link_packages

    link_targets = []

    if link:
        if bazel_package == "":
            link_targets.append("//{}:{}/@aspect-test/b".format(bazel_package, name))
            link_targets.append("//{}:{}/is-odd".format(bazel_package, name))
    return link_targets
