"""@generated by npm_translate_lock(name = "npm", pnpm_lock = "//:pnpm-lock.yaml")"""

load("@aspect_rules_js//npm:repositories.bzl", "npm_import")

# Generated npm_import repository rules corresponding to npm packages in //:pnpm-lock.yaml
# buildifier: disable=function-docstring
def npm_repositories():
    npm_import(
        name = "npm__at_aspect-test_a__5.0.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@aspect-test/a",
        version = "5.0.2",
        url = "https://registry.npmjs.org/@aspect-test/a/-/a-5.0.2.tgz",
        package_visibility = ["//visibility:public"],
        npm_translate_lock_repo = "npm",
        integrity = "sha512-bURS+F0+tS2XPxUPbrqsTZxIre1U5ZglwzDqcOCrU7MbxuRrkO24hesgTMGJldCglwL/tiEGRlvdMndlPgRdNw==",
        deps = {
            "@aspect-test/b": "5.0.2",
            "@aspect-test/c": "2.0.2",
            "@aspect-test/d": "2.0.0_at_aspect-test_c_2.0.2",
        },
        transitive_closure = {
            "@aspect-test/a": ["5.0.2"],
            "@aspect-test/b": ["5.0.2"],
            "@aspect-test/c": ["2.0.2"],
            "@aspect-test/d": ["2.0.0_at_aspect-test_c_2.0.2"],
        },
    )

    npm_import(
        name = "npm__at_aspect-test_b__5.0.2",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["@aspect-test/b"],
        },
        package = "@aspect-test/b",
        version = "5.0.2",
        url = "https://registry.npmjs.org/@aspect-test/b/-/b-5.0.2.tgz",
        package_visibility = ["//visibility:public"],
        npm_translate_lock_repo = "npm",
        integrity = "sha512-I8wnJV5J0h8ui1O3K6XPq1qGHKopTl/OnvkSfor7uJ9yRCm2Qv6Tf2LsTgR2xzkgiwhA4iBwdYFwecwinF244w==",
        deps = {
            "@aspect-test/a": "5.0.2",
            "@aspect-test/c": "2.0.2",
            "@aspect-test/d": "2.0.0_at_aspect-test_c_2.0.2",
        },
        transitive_closure = {
            "@aspect-test/a": ["5.0.2"],
            "@aspect-test/b": ["5.0.2"],
            "@aspect-test/c": ["2.0.2"],
            "@aspect-test/d": ["2.0.0_at_aspect-test_c_2.0.2"],
        },
    )

    npm_import(
        name = "npm__at_aspect-test_c__2.0.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@aspect-test/c",
        version = "2.0.2",
        url = "https://registry.npmjs.org/@aspect-test/c/-/c-2.0.2.tgz",
        package_visibility = ["//visibility:public"],
        npm_translate_lock_repo = "npm",
        integrity = "sha512-rMJmd3YBvY7y0jh+2m72TiAhe6dVKjMMNFFVOXFCbM233m7lsG4cq970H1C8rUsc3AcA5E/cEHlxSVffHlHD2Q==",
        transitive_closure = {
            "@aspect-test/c": ["2.0.2"],
        },
        lifecycle_hooks = ["preinstall", "install", "postinstall"],
        lifecycle_hooks_execution_requirements = ["no-sandbox"],
    )

    npm_import(
        name = "npm__at_aspect-test_d__2.0.0__at_aspect-test_c_2.0.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@aspect-test/d",
        version = "2.0.0_at_aspect-test_c_2.0.2",
        url = "https://registry.npmjs.org/@aspect-test/d/-/d-2.0.0.tgz",
        package_visibility = ["//visibility:public"],
        npm_translate_lock_repo = "npm",
        integrity = "sha512-jndwr8pLUfn795uApTcXG/yZ5hV2At1aS/wo5BVLxqlVVgLoOETF/Dp4QOjMHE/SXkXFowz6Hao+WpmzVvAO0A==",
        deps = {
            "@aspect-test/c": "2.0.2",
        },
        transitive_closure = {
            "@aspect-test/c": ["2.0.2"],
            "@aspect-test/d": ["2.0.0_at_aspect-test_c_2.0.2"],
        },
    )

    npm_import(
        name = "npm__is-number__6.0.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "is-number",
        version = "6.0.0",
        url = "https://registry.npmjs.org/is-number/-/is-number-6.0.0.tgz",
        package_visibility = ["//visibility:public"],
        npm_translate_lock_repo = "npm",
        integrity = "sha512-Wu1VHeILBK8KAWJUAiSZQX94GmOE45Rg6/538fKwiloUu21KncEkYGPqob2oSZ5mUT73vLGrHQjKw3KMPwfDzg==",
        transitive_closure = {
            "is-number": ["6.0.0"],
        },
    )

    npm_import(
        name = "npm__is-odd__3.0.1",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["is-odd"],
        },
        package = "is-odd",
        version = "3.0.1",
        url = "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz",
        package_visibility = ["//visibility:public"],
        npm_translate_lock_repo = "npm",
        integrity = "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==",
        deps = {
            "is-number": "6.0.0",
        },
        transitive_closure = {
            "is-number": ["6.0.0"],
            "is-odd": ["3.0.1"],
        },
    )
